### ISSUE TITLE
seems backgound of some gtk3 apps are now (back again) transparent

### ISSUE THREAD

**Issue by mckaygerhard** [cat-in-136/FlatSurfacesTheme#11]
i already know this is suppost to been resolved at #4  but now seems is back, only when i try to use mate desktop (i not tested in gnomecrap or xfce4)

in lxde seems to work good and into openbox (no desktop, only windown manager), normal theme works, all the mate and gnome themes are installed and pixbuf engine

![image](https://github.com/cat-in-136/FlatSurfacesTheme/assets/1571724/c61a9360-17fe-4a70-b045-f20ada9ebe0a)

The normal theme is working

![image](https://github.com/cat-in-136/FlatSurfacesTheme/assets/1571724/f3df036c-0840-4092-aa97-e405a916a37a)

**Comment by cat-in-136** [comment]
@mckaygerhard It is very helpful if the issue can be reproduced on Live DVD (without installation).

**Comment by mckaygerhard** [comment]
umm please give me until sunday, i will need to free ram and boot it some live systems into qemu

**Comment by mckaygerhard** [comment]
ok today i used the winbuntu crap 20.04 LTS a valid LTS supported system today (to the right) and my beloved debian (but the crap of last verison 12, to the left) .. tomorrow i will test using my daily system, debian 8 jessie and alpine 3.10.

in winbuntu the "onthenight" theme is not rendered.. below at the end the systems differences

![image](https://github.com/cat-in-136/FlatSurfacesTheme/assets/1571724/1fa01d17-bc3e-4588-a855-a198c17805d7)

### Detailed install:

**Winbuntu 20.04 LTS** : linux 5.15 , glibc 2.32, glib 2.64 (lilbglib2.0-0 + libglib2.0-bin).  GTK3 3.24.20 (libgtk-3-0 + libgtk-3-0-bin), gdk-pixbuf 2.40 (libgdk-pixbuf2.0-0 agains gtk3), GTK2 2.24.32 (libgtk2.0-0 + libgtk2.0-bin)

**Debian 12** : linux 6.1 , glibc 2.34, glib 2.74 (lilbglib2.0-0 + libglib2.0-bin).  GTK3 3.24.38 (libgtk-3-0 + libgtk-3-0-bin), gdk-pixbuf 2.42 (libgdk-pixbuf2.0-0 agains gtk3), GTK2 2.24.33 (libgtk2.0-0 + libgtk2.0-bin)


Both have installed also:

* gtk2-engines  (for gtk2 hcengine or high contrast engine)
* mate-thems for older high-contrast theme, hcengine for gtk3 its suppost to include hcengine
* gnome-accesibility-themes

**i noted that gtk4 now have their own way to make inverted colors.. maybe gnome shit developers removed the hcengine ..**

**Comment by mckaygerhard** [comment]
i tested again in debian 8 jessie from 6 years ago .. older releae and there it works like a charm.. but in recents winbuntus does not work.. i will test again later in alpine today.. 

so in resume:

* debian 12 : works all the gtk versions dark and light
* debian 8 : works all the gtk versions dark and light
* debian 9 : fails in dark only in mate desktop
* winbuntu 20 lts : fails the background of dark flavour

**Comment by cat-in-136** [comment]
It would be very funny and cool if my theme works well on winbuntu 20 lts. Because, as your comment states, winbuntu is "crap". To be more specific, winbuntu is madly trying to look like windows appearance, whereas the attempt to apply a completely different FlatSurface look to it is very challenging. Sure, it is a very cool hobby.

However, such a cool hobby should be done on your personal blog, for example. Your comments are not coherent and frankly just noise to me. You report it doesn't work with too-old debian 9? Are you kidding me?

I don't even mean to deny your cool hobby. If you create a PR to support winbuntu, I would accept your PR. if you "will be as god OF COURSE STUPID with high tech!" in your word in your profile, I can merge your stupid high-tech code.

**Comment by mckaygerhard** [comment]
well men! that is.. it works in alpine i just tried.. and works in others rare live disk like parriot but i limited to only popular distros.. i was thinking in tried mint later.. but need more ram for.. so i just post what is.. nothing more
