### ISSUE TITLE
newr gtks have so much space in menu elements

### ISSUE THREAD

**Issue by mckaygerhard** [cat-in-136/FlatSurfacesTheme#7]
hi great work .. i was with hope and now you have the 0.8 with gtk3 working.. thanks.. 

noted the new gtk4 branch also.. i will report feedback too (in new issue)

here issues:

- [x] big space between elements of menues in gtk3 72a1534a88241512f5602ebf459d59b038f67f3f
- [x] some big spaces in styling of some widget/parts on gtk3 engine 72a1534a88241512f5602ebf459d59b038f67f3f

### big space between elements of menues in gtk3

menues in gtk2 are great and elements are compact and concise, no waste of space..(right side of the picture) ideal for high or reduced screens.. 

but not for gtk3, there are too much space beetween elements (left side of the picture)

![image](https://github.com/cat-in-136/FlatSurfacesTheme/assets/1571724/69f4f7ec-5ac6-4e69-bee2-f60fb8ba0cab)

### rendering of gtk3 cleint side decoratinos have a rare shadow or forced composite

here border of client side decorations have a rare "not valid" (its not touchable by mouse pointer) in black, in some gpus:

![image](https://github.com/cat-in-136/FlatSurfacesTheme/assets/1571724/e4c3feef-c761-4e08-8a25-d2631bd700b0)

**Comment by cat-in-136** [comment]
Thank you for reporting.

* "big space between elements of menues in gtk3"
  * I acknowledge the issue was introduced as a regression from my PR #6. I have created a PR #9 to minimize the padding of menu items to zero.
* "some big spaces in styling of some widget/parts on gtk3 engine" 
  * It's important to clarify that application-specific widget design falls outside the remit of this project. The diversity of applications and the specificity of their widget designs make it an unbounded task. Additionally, as I do not use Google Chrome, my lack of familiarity with its interface nuances might lead to suboptimal adjustments. Although I'm aware of the broad usage of Chromium/Google Chrome, my project policy might not align with the expectations of their users. Nevertheless, if a PR provided, I am open to merging it.
* "rendering of gtk3 cleint side decoratinos have a rare shadow or forced composite"
  * Indeed, the decision to style borders sparingly is informed by the varying behaviors of different window manager combinations and desktop composition settings. In addition, border dragging is rarely necessary for window resizing. Alt+right-drag is a longstanding feature, which I know it was used on the classic twm window manager. So, I believe that sparingly border design is not against to the philosophy of my "old look" design theme.

**Comment by mckaygerhard** [comment]
> Thank you for reporting.
> 

i use it so much your theme

> * "rendering of gtk3 cleint side decoratinos have a rare shadow or forced composite"
>   
>   * Indeed, the decision to style borders sparingly is informed by the varying behaviors of different window manager combinations and desktop composition settings. In addition, border dragging is rarely necessary for window resizing. Alt+right-drag is a longstanding feature, which I know it was used on the classic twm window manager. So, I believe that sparingly border design is not against to the philosophy of my "old look" design theme.

**sorry i found that this is named shadown client decoration, must be a way to disable shadow client decoration?** @cat-in-136  ?

> * "big space between elements of menues in gtk3"
>   
>   * I acknowledge the issue was introduced as a regression from my PR [rewrite all of gtk-3.20/gtk-widges.css #6](https://github.com/cat-in-136/FlatSurfacesTheme/pull/6). I have created a PR [make menuitem padding to zero on gtk-3.20 #9](https://github.com/cat-in-136/FlatSurfacesTheme/pull/9) to minimize the padding of menu items to zero.
> * "some big spaces in styling of some widget/parts on gtk3 engine"

men .. that was so fast!

>   
>   * It's important to clarify that application-specific widget design falls outside the remit of this project. The diversity of applications and the specificity of their widget designs make it an unbounded task. Additionally, as I do not use Google Chrome, my lack of familiarity with its interface nuances might lead to suboptimal adjustments. Although I'm aware of the broad usage of Chromium/Google Chrome, my project policy might not align with the expectations of their users. Nevertheless, if a PR provided, I am open to merging it.

ok i was trying to get more info and seems many themes has specific tricks to that.. i am not talking about only chrome app, i will try to clarify in the future this.. sorry to not be enought clear.. thanks in any case and i will try to get more deep into the issue
